name: CI                        # Workflow name (can be anything)
on:                             # On any push to the main branch
  push:
    branches:
      - "main"
jobs:                           # Run a job
  build:                        # called `build`
    runs-on: ubuntu-latest      # On an Ubuntu VM
    steps:                      # with these steps
      - uses: actions/checkout@v3 # checkout the repository
     
      - run: curl -L https://github.com/hasura/graphql-engine/raw/master/cli/get.sh | bash
      - run: hasura deploy --endpoint https://cute-marlin-52.hasura.app --admin-secret c82FQh9ITxMNxnxXvUCQww1JkOYTUiH5E04Usdsr1TccMdi1ill9Cjas0PE0wp4Z . # then use the hasura CLI to deploy using repository secrets
      - run: hasura metadata reload --endpoint https://cute-marlin-52.hasura.app --admin-secret c82FQh9ITxMNxnxXvUCQww1JkOYTUiH5E04Usdsr1TccMdi1ill9Cjas0PE0wp4Z . 
